[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-freefont"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["npm run build:all"]

[start]
cmd = "node start-prod.js"

